language: python
python:
  - "3.8"

virtualenv:
  system_site_packages: true

before_install:
  - sudo apt-get install -qq python-numpy python-scipy

script:
  - python fiber.py
  - python trarrays.py
  - python utils.py
